name: build and test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    name: build-and-test
    strategy:
      matrix:
        include: 
          - { name: Linux, python: '3.9', os: ubuntu-latest }
          - { name: Windows, python: '3.9', os: windows-latest }
          - { name: Mac, python: '3.9', os: macos-latest }
          - { name: Linux, python: '3.8', os: ubuntu-latest }
          - { name: Linux, python: '3.7', os: ubuntu-latest }
          - { name: Linux, python: '3.6', os: ubuntu-latest }
          - { name: Linux, python: '3.7', os: ubuntu-20.04 }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - run: python -m pip install --upgrade pip wheel
    - run: pip install tox tox-gh-actions
    - run: tox
